apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: apikey-plugin
config: 
  key_names:
  - x-api-key
  key_in_body: false
  key_in_header: true
  key_in_query: false
  hide_credentials: false
  run_on_preflight: true
plugin: key-auth