apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: httpbin-service-config
proxy:
  protocol: http
  path: /
  retries: 10
  connect_timeout: 10000
  read_timeout: 10000
  write_timeout: 10000
upstream:
  healthchecks:
    active:
      healthy:
        interval: 5
        successes: 3
        http_statuses:
        - 200
      http_path: /status/200
      type: http
      unhealthy:
        http_failures: 1
        interval: 5
        http_statuses:
        - 500
    passive:
      healthy:
        successes: 3
        http_statuses:
        - 200
      unhealthy:
        http_failures: 3
        http_statuses:
        - 500